// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.AlfaVisionWebModels;

public partial class AlfaVisionWebEntities : DbContext
{
    public AlfaVisionWebEntities(DbContextOptions<AlfaVisionWebEntities> options)
        : base(options)
    {
    }

    public virtual DbSet<IncludedDriver> IncludedDrivers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<IncludedDriver>(entity =>
        {
            entity.HasKey(e => e.incDrvID)
                .IsClustered(false)
                .HasAnnotation("SqlServer:FillFactor", 100);

            entity.HasIndex(e => e.PolicyNo, "IX_IncludedDriver_policyno")
                .IsClustered()
                .HasFillFactor(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}