// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("ALIATransactionLog", Schema = "dbo")]
public partial class ALIATransactionLog
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string AlfaTransactionNumber { get; set; }

    [Required]
    [StringLength(50)]
    public string PolicyNumber { get; set; }

    [Required]
    public string PayloadSent { get; set; }

    [Required]
    public string PayloadReceived { get; set; }

    [StringLength(8)]
    public string MembershipNumber { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    [Required]
    [StringLength(10)]
    public string ApiCalled { get; set; }

    [StringLength(10)]
    public string QuoteId { get; set; }

    public bool? MembershipFlag { get; set; }

    public bool? PacFlag { get; set; }

    [StringLength(50)]
    public string MemberName { get; set; }

    public bool? FailNameCheck { get; set; }
}