// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("ISODrivers", Schema = "dbo")]
[Index("QuoteID", Name = "IX_ISODrivers_Quoteid")]
[Index("sdID", Name = "IX_ISODrivers_sdID")]
public partial class ISODrivers
{
    [Key]
    public int ISODrvID { get; set; }

    public int QuoteID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string MiddleInitial { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string LastName { get; set; }

    public byte[] DOBEncrypted { get; set; }

    public byte[] SSNEncrypted { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Gender { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Marital { get; set; }

    public byte[] DLNEncrypted { get; set; }

    public bool Accepted { get; set; }

    public bool Duplicate { get; set; }

    public int RejectionType { get; set; }

    public int sdID { get; set; }

    public int? rowId { get; set; }

    public int? ISOMasterId { get; set; }
}