// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("ISOVehicles", Schema = "dbo")]
[Index("QuoteID", Name = "IX_ISOVehicles_Quoteid")]
[Index("QuoteID", "VIN", Name = "IX_QuoteID_VIN")]
public partial class ISOVehicles
{
    [Key]
    public int isoVehID { get; set; }

    public int QuoteID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string VIN { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string VINiso { get; set; }

    public int? ModelYear { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Make { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ShortModelName { get; set; }

    public bool Accepted { get; set; }

    public int? rowId { get; set; }

    public int? ISOMasterId { get; set; }

    public int? SvId { get; set; }

    public int? RejectionType { get; set; }
}