// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CommonAPIDAL.VisionAppModels;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace CommonAPIDAL.VisionAppModels
{
    public partial interface IVisionAppEntitiesProcedures
    {
        Task<List<spGetAFFNewMemberDataResult>> spGetAFFNewMemberDataAsync(int? quoteID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetMemberSearchDataResult>> spGetMemberSearchDataAsync(string quoteID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spRAPA2UpdateSelectedDetailAsync(int? QuoteID, string VIN, int? Seq, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspGetVINDataByManufacturerIDResult>> uspGetVINDataByManufacturerIDAsync(string ManufacturerID, string State, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspGetVINDataByManufacturerIDLegacyResult>> uspGetVINDataByManufacturerIDLegacyAsync(string ManufacturerID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspVinLookup_MannufacturerID_TypeResult>> uspVinLookup_MannufacturerID_TypeAsync(string ManufacturerID, string State, string PrimaryorSupplementalFlag, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
