// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

/// <summary>
/// Make Model Identity key
/// </summary>
[Keyless]
[Table("MakeModelLookup", Schema = "dbo")]
[Index("ModelYear", Name = "IX_MakeModelLookup_ModelYear")]
[Index("ModelYear", "MakeCode", Name = "IX_MakeModelLookup_ModelYear_MakeCode")]
public partial class MakeModelLookup
{
    public int MakeModelID { get; set; }

    public short ModelYear { get; set; }

    [Required]
    [StringLength(4)]
    [Unicode(false)]
    public string MakeCode { get; set; }

    [StringLength(39)]
    [Unicode(false)]
    public string FullModelName { get; set; }
}