// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("ProgramRevision", Schema = "dbo")]
[Index("ProgramID", "RevisionNum", "StartDate", "EndDate", Name = "IX_ProgramRevision_Unique", IsUnique = true)]
public partial class ProgramRevision
{
    [Key]
    public int ProgramRevID { get; set; }

    public int ProgramID { get; set; }

    public short RevisionNum { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime EndDate { get; set; }

    public int? PrevVal { get; set; }

    public int? NextVal { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string RateBookCode { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? RenewalStartDate { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? RenewalEndDate { get; set; }

    public byte? MinimumListedAge { get; set; }

    public byte? CurrentCarrierAgeCutoff { get; set; }

    public byte? CreditAgeCutoff { get; set; }

    [Column(TypeName = "decimal(9, 2)")]
    public decimal MVRDollarCutoff { get; set; }

    public byte? ClaimsMonthsCutoff { get; set; }

    public bool? UseAttract30 { get; set; }

    public bool? UseISO { get; set; }

    public bool? UsePaperless { get; set; }

    public bool? UseERA { get; set; }

    public int? ProgramRevBaseID { get; set; }

    public bool? UseAPLUS { get; set; }

    public bool AtmVerifyEft { get; set; }

    public int? MaxISO { get; set; }

    public int? MaxComp { get; set; }

    public int? MaxColl { get; set; }

    public bool? UseISOCV { get; set; }

    public bool RequiresPriorInsuranceForEFTRecurring { get; set; }

    public bool? UsePredictor { get; set; }

    public bool? UseRAPA { get; set; }

    public bool? UseVehicleScore { get; set; }

    public int? RAPAVersion { get; set; }

    [ForeignKey("ProgramID")]
    [InverseProperty("ProgramRevision")]
    public virtual ProgramMaster Program { get; set; }

    [InverseProperty("ProgramRev")]
    public virtual ICollection<Staging_Policy> Staging_Policy { get; set; } = new List<Staging_Policy>();
}