// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("Rapa2_BodyInfo", Schema = "dbo")]
public partial class Rapa2_BodyInfo
{
    [Key]
    public int biId { get; set; }

    [Required]
    [StringLength(8)]
    public string BodyInfoCode { get; set; }

    [Required]
    [StringLength(50)]
    public string BodyInfoDesc { get; set; }
}