// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("Rapa2_Chassis", Schema = "dbo")]
public partial class Rapa2_Chassis
{
    [Key]
    public int chId { get; set; }

    [Required]
    [StringLength(8)]
    public string ChassisCode { get; set; }

    [Required]
    [StringLength(50)]
    public string ChassisDesc { get; set; }
}