// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("Rapa2_VinSearchAuditHdr", Schema = "dbo")]
public partial class Rapa2_VinSearchAuditHdr
{
    [Key]
    public int HdrId { get; set; }

    [Required]
    [StringLength(50)]
    public string TransactionID { get; set; }

    [Required]
    [StringLength(50)]
    public string Vin { get; set; }

    [StringLength(50)]
    public string PolicyNbr { get; set; }

    public int? QuoteId { get; set; }

    [Required]
    public string Response { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [StringLength(150)]
    public string RapaParm { get; set; }
}