// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("Rapa2_Make", Schema = "dbo")]
public partial class Rapa2_Make
{
    [Key]
    public int MakeId { get; set; }

    [Required]
    [StringLength(8)]
    public string MakeIsoCode { get; set; }

    [Required]
    [StringLength(8)]
    public string MakeNcicCode { get; set; }

    [Required]
    [StringLength(50)]
    public string MakeDesc { get; set; }
}