// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("Rapa2_VinSearchAuditDtl", Schema = "dbo")]
public partial class Rapa2_VinSearchAuditDtl
{
    [Key]
    public int DetailId { get; set; }

    public int HdrId { get; set; }

    public bool Selected { get; set; }

    [Required]
    [StringLength(17)]
    public string VIN { get; set; }

    public int? MakeCode { get; set; }

    [StringLength(50)]
    public string BasicModelName { get; set; }

    public int? ModelYear { get; set; }

    public int? DistributionDate { get; set; }

    [StringLength(1)]
    public string Restraint { get; set; }

    [StringLength(1)]
    public string AntiLockBrakes { get; set; }

    [StringLength(1)]
    public string EngineCylinders { get; set; }

    [StringLength(1)]
    public string EngineType { get; set; }

    [StringLength(10)]
    public string BodyStyle { get; set; }

    [Column(TypeName = "decimal(4, 1)")]
    public decimal? EngineSize { get; set; }

    [StringLength(1)]
    public string FourWheelDriveIndicator { get; set; }

    [StringLength(1)]
    public string ElectronicStabilityControl { get; set; }

    [StringLength(50)]
    public string FullModelName { get; set; }

    public int? ClassCode { get; set; }

    [StringLength(1)]
    public string AntiTheftIndicator { get; set; }

    public int? CurbWeight { get; set; }

    public int? GrossVehicleWeight { get; set; }

    public int? Horsepower { get; set; }

    [StringLength(2)]
    public string StateException { get; set; }

    [StringLength(1)]
    public string VMPerformanceIndicator { get; set; }

    [StringLength(1)]
    public string SpecialHandlingIndicator { get; set; }

    [StringLength(1)]
    public string InterimIndicator { get; set; }

    [StringLength(1)]
    public string SpecialInfoSelector { get; set; }

    [StringLength(4)]
    public string ModelSeriesInfo { get; set; }

    [StringLength(4)]
    public string BodyInfo { get; set; }

    [StringLength(4)]
    public string EngineInfo { get; set; }

    [StringLength(4)]
    public string RestraintInfo { get; set; }

    public int? ReleaseDate { get; set; }

    public int? Sequence { get; set; }

    public int? MSRP { get; set; }
}