// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("Rapa2_EngineInformation", Schema = "dbo")]
public partial class Rapa2_EngineInformation
{
    [Key]
    public int eiId { get; set; }

    [Required]
    [StringLength(8)]
    public string EngineInformationCode { get; set; }

    [Required]
    [StringLength(100)]
    public string EngineInformationDesc { get; set; }
}