// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Keyless]
[Table("Rapa2_Limits", Schema = "dbo")]
public partial class Rapa2_Limits
{
    public int Id { get; set; }

    [Required]
    [StringLength(2)]
    public string State { get; set; }

    public int MSRPLimit { get; set; }

    public int WeightLimit { get; set; }

    public bool UseCappedSymbols { get; set; }
}