// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("Rapa2_AntiTheftIndicator", Schema = "dbo")]
public partial class Rapa2_AntiTheftIndicator
{
    [Key]
    public int atId { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string AntiTheftCode { get; set; }

    [Required]
    [StringLength(50)]
    public string AntiTheftDesc { get; set; }
}