// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("Rapa2_EngineType", Schema = "dbo")]
public partial class Rapa2_EngineType
{
    [Key]
    public int etId { get; set; }

    [Required]
    [StringLength(8)]
    public string EngineTypeCode { get; set; }

    [Required]
    [StringLength(50)]
    public string EngineTypeDesc { get; set; }
}