// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("Rapa2_AntiLockBrakeIndicator", Schema = "dbo")]
public partial class Rapa2_AntiLockBrakeIndicator
{
    [Key]
    public int absId { get; set; }

    [Required]
    [StringLength(8)]
    public string ABSCode { get; set; }

    [Required]
    [StringLength(150)]
    public string ABSDesc { get; set; }
}