// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("Rapa2_BodyStyle", Schema = "dbo")]
public partial class Rapa2_BodyStyle
{
    [Key]
    public int bsId { get; set; }

    [Required]
    [StringLength(8)]
    public string BodyStyleCode { get; set; }

    [Required]
    [StringLength(50)]
    public string BodyStyleDesc { get; set; }
}