// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CommonAPIDAL.VisionAppModels
{
    public partial class spGetAFFNewMemberDataResult
    {
        public string InsAddress1 { get; set; }
        public string InsAddress2 { get; set; }
        public string InsCity { get; set; }
        public string InsState { get; set; }
        public string InsZip { get; set; }
        public string LoginName { get; set; }
        public string agentNumber { get; set; }
        public string comments { get; set; }
        public string dateOfBirth { get; set; }
        public string InsEmail { get; set; }
        public string phoneNumber { get; set; }
        public string InsFirstName { get; set; }
        public string InsLastName { get; set; }
        public string SecondaryFirstName { get; set; }
        public string SecondaryLastName { get; set; }
        public string Column1 { get; set; }
        public string status { get; set; }
        public string typeIndicator { get; set; }
    }
}
