// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CommonAPIDAL.VisionAppModels
{
    public partial class spGetMemberSearchDataResult
    {
        public string InsFirstName { get; set; }
        public string InsLastName { get; set; }
        public string InsAddress1 { get; set; }
        public string InsAddress2 { get; set; }
        public string InsCity { get; set; }
        public string InsState { get; set; }
        public string InsZip { get; set; }
    }
}
