// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("Staging_Applicant", Schema = "dbo")]
[Index("ApplicantNum", Name = "IX_StagingApplicant_AppNum")]
[Index("ApplicantNum", "InsLastName", Name = "IX_Staging_Applicant_ApplicantNum_InsLastName")]
[Index("ApplicantNum", "InsState", "InsAddress1", Name = "IX_Staging_Applicant_ApplicantNum_InsState_InsAddress1")]
[Index("QuoteID", "EndorsementAction", Name = "IX_Staging_Applicant_QuoteIDEndorsemenentAction")]
[Index("apID", "HasPriorInsuranceFlag", "PriorLapseCharacteristicDetailID", "PriorLimitCharacteristicDetailID", "PriorLapseID", "PriorLimitID", "InsLastName", Name = "IX_Staging_Applicant_QuoteID_HasPriorInsuranceFlag")]
[Index("apID", "QuoteID", "ApplicantNum", "InsLastName", "InsFirstName", Name = "IX_Staging_Applicant_Search")]
[Index("QuoteID", "ApplicantNum", "InsFirstName", "InsLastName", Name = "IX_Staging_Applicant_search2")]
[Index("QuoteID", "ApplicantNum", Name = "IX_Staging_Applicant_unique", IsUnique = true)]
public partial class Staging_Applicant
{
    [Key]
    public int apID { get; set; }

    public int QuoteID { get; set; }

    public short ApplicantNum { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string InsFirstName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string InsMidName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string InsLastName { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string InsSuffixName { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string InsAddress1 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string InsAddress2 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string InsCity { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string InsState { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string InsZip { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string InsCounty { get; set; }

    [StringLength(12)]
    [Unicode(false)]
    public string InsPhone1 { get; set; }

    [StringLength(12)]
    [Unicode(false)]
    public string InsPhone2 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string InsEmail { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string TaxJurisdiction { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string GarAddress { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string GarAddress2 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string GarCity { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string GarState { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string GarZip { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string GarCounty { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string GarTerritory { get; set; }

    public bool InsideCityLimits { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Municipality { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string EndorsementAction { get; set; }

    /// <summary>
    /// (M)anul, (T)ritech
    /// </summary>
    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string TaxJurisdictionAssignBy { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PriorInsCoName { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string PriorPolStandardInd { get; set; }

    public short? CreditScore { get; set; }

    public int? PriorLapseID { get; set; }

    public int? PriorLimitID { get; set; }

    public long? ClientID { get; set; }

    public bool PriorInsManualOverride { get; set; }

    [StringLength(6)]
    [Unicode(false)]
    public string CountyCode { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string DocumentDeliveryMethod { get; set; }

    [StringLength(12)]
    [Unicode(false)]
    public string InsPhone3 { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string AS400InsType { get; set; }

    public int? PriorLapseCharacteristicDetailID { get; set; }

    public int? PriorLimitCharacteristicDetailID { get; set; }

    public bool? HasPriorInsuranceFlag { get; set; }
}