// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("Staging_Vehicle", Schema = "dbo")]
[Index("BiSymbol", Name = "IXNC_Staging_Vehicle_BiSymbol_7EB12")]
[Index("MakeID", "BiSymbol", Name = "IXNC_Staging_Vehicle_MakeID_BiSymbol_CB38B")]
[Index("VIN", Name = "IXNC_Staging_Vehicle_VIN")]
[Index("vsId", Name = "IXNC_Staging_Vehicle_vsId_60EE1")]
[Index("vsId", Name = "IXNC_Staging_Vehicle_vsId_BA72C")]
[Index("PIPSymbol", "LiabilitySymbol", Name = "IX_Staging_Vehicle_LiabilitySymbol_PIPSymbol")]
public partial class Staging_Vehicle
{
    [Key]
    public int svID { get; set; }

    public int QuoteID { get; set; }

    public byte VehicleNum { get; set; }

    public byte? RatedDrvNum { get; set; }

    public byte? PrimaryDrvNum { get; set; }

    public int? MakeID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Model { get; set; }

    public short? ModelYear { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string VIN { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string ISOSymbol { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string LiabilitySymbol { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string PIPSymbol { get; set; }

    public int? UsageID { get; set; }

    public int? AnnualMiles { get; set; }

    public int? Odometer { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string GarTerritory { get; set; }

    public byte? VehiclePoints { get; set; }

    public bool NamedOperator { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string ISOVIN { get; set; }

    public bool VINAccepted { get; set; }

    public bool ModelNotFound { get; set; }

    public bool RateReady { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string EndorsementAction { get; set; }

    public int? CommuteMiles { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string CompSymbol { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string CollSymbol { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string NewPriceSymbol { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? VehAddedDate { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string BiSymbol { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string PDSymbol { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string MedPaySymbol { get; set; }

    public bool? IsFinanced { get; set; }

    public bool? AdditionalInterest { get; set; }

    public int? vsId { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string VScore { get; set; }

    public bool? AcceptVSNoHit { get; set; }

    public bool? Supplemental { get; set; }

    public int? RAPAVersion { get; set; }

    [InverseProperty("sv")]
    public virtual ICollection<Staging_Coverage> Staging_Coverage { get; set; } = new List<Staging_Coverage>();
}