// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("Staging_Coverage", Schema = "dbo")]
[Index("svID", Name = "IXNC_Staging_Coverage_svID_22EC6")]
[Index("svID", "Cov", "ProgramRevCoverageDetailID", "ProgramRevDeductibleDetailID", "Premium", "EndorsementAction", Name = "IX_Staging_Coverage_Covering1")]
[Index("svID", "ProgramRevCoverageDetailID", "ProgramRevDeductibleDetailID", Name = "IX_Staging_Coverage_unique", IsUnique = true)]
public partial class Staging_Coverage
{
    [Key]
    public int scvID { get; set; }

    public int svID { get; set; }

    [Required]
    [StringLength(3)]
    [Unicode(false)]
    public string Cov { get; set; }

    public int? ProgramRevCoverageDetailID { get; set; }

    public int? ProgramRevDeductibleDetailID { get; set; }

    [Column(TypeName = "decimal(9, 2)")]
    public decimal? Premium { get; set; }

    [Column(TypeName = "decimal(9, 2)")]
    public decimal? CustomLimit { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string EndorsementAction { get; set; }

    [ForeignKey("svID")]
    [InverseProperty("Staging_Coverage")]
    public virtual Staging_Vehicle sv { get; set; }
}