// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("Staging_Policy", Schema = "dbo")]
[Index("RMID", Name = "IDX_Staging_Policy_RMID")]
[Index("ReceivedTime", Name = "IXNC_SP_RT")]
[Index("RateStatusID", Name = "IXNC_Staging_Policy_RateSID")]
[Index("RateStatusID", Name = "IXNC_Staging_Policy_RateStatusID_9E437")]
[Index("RaterID", "RateStatusID", "LastModified", Name = "IXNC_Staging_Policy_RaterID_RateStatusID_LastModified_8F7CF")]
[Index("LastRated", "RateStatusID", Name = "IX_Staging_Policy_LastRated_RateStatusID")]
[Index("MemberID", Name = "IX_Staging_Policy_Memberid")]
[Index("ProducerCode", Name = "IX_Staging_Policy_ProducerCode")]
[Index("ProducerCode", Name = "IX_Staging_Policy_ProducerCodePC")]
[Index("ProducerCode", "Deleted", "ReceivedTime", "RateStatusID", Name = "IX_Staging_Policy_ProducerCode_Deleted_ReceivedTime_RateStatusID")]
[Index("ProgramRevID", "LastRated", "RateStatusID", Name = "IX_Staging_Policy_ProgramRevID_LastRated_RateStatusID")]
[Index("RateStatusID", Name = "IX_Staging_Policy_RateStatusID")]
[Index("RateStatusID", "FullPolNum", Name = "IX_Staging_Policy_RateStatusID_FullPolNum")]
[Index("RateStatusID", "ISOMasterID", Name = "IX_Staging_Policy_RateStatusID_ISOMasterID")]
[Index("RateStatusID", "LastModified", Name = "IX_Staging_Policy_RateStatusID_LastModified")]
[Index("RateStatusID", "LastRated", Name = "IX_Staging_Policy_RateStatusID_LastRated")]
[Index("RateStatusID", "ReceivedTime", Name = "IX_Staging_Policy_RateStatusID_ReceivedTime")]
[Index("FullPolNum", "ProducerCode", Name = "IX_Staging_Policy_fullPolNum")]
[Index("lrID", Name = "IX_Staging_Policy_lrID")]
[Index("ProgramRevID", "QuoteID", Name = "IX_Staging_Policy_progRevID")]
[Index("ProgramRevID", "ReceivedTime", Name = "NCI_SP_PREVID_RT")]
[Index("RateStatusID", Name = "NCI_SP_RSID")]
[Index("ReceivedTime", Name = "NCI_SP_RT")]
public partial class Staging_Policy
{
    [Key]
    public int QuoteID { get; set; }

    public int? ProgramRevID { get; set; }

    public int? RaterID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ReceivedTime { get; set; }

    [Column(TypeName = "decimal(9, 0)")]
    public decimal? PolNum { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? EffDate { get; set; }

    public int? TermID { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string ProducerCode { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string RemoteIP { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastModified { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastRated { get; set; }

    public bool IsDirty { get; set; }

    public short RateStatusID { get; set; }

    public int? MemberID { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string FullPolNum { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string BridgePath { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string BridgeVersion { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string RaterVersion { get; set; }

    public short SequenceID { get; set; }

    public bool Deleted { get; set; }

    public byte? RecurringPmt { get; set; }

    public bool MVRNoHitAcceptance { get; set; }

    public byte? LastDriver { get; set; }

    public byte? LastVehicle { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? TermEffDate { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? TermExpDate { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? LastLapseDate { get; set; }

    public bool HasOpenClaim { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? OriginalEffDate { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string MembershipNum { get; set; }

    public bool MembershipDues { get; set; }

    public bool CreditPulled { get; set; }

    public int? RMID { get; set; }

    public bool? CCAcceptance { get; set; }

    public bool? ProgramChange { get; set; }

    public bool? QuoteWithCredit { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string EFTPaymentType { get; set; }

    public bool? InspectionFormConfirm { get; set; }

    public bool? UnsoldQuote { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string EFTRecurringAction { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string OptOutCreditScore { get; set; }

    public bool WasPrefillEntered { get; set; }

    public int? lrID { get; set; }

    public int? ISOMasterID { get; set; }

    public byte? LastRatedDriver { get; set; }

    public bool IsRewrite { get; set; }

    [Column(TypeName = "decimal(9, 0)")]
    public decimal? RewrittenFromPolicyNumber { get; set; }

    public byte? LastListOnlyDriver { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? LossDate { get; set; }

    public int? CSRID { get; set; }

    public bool FarmPACFee { get; set; }

    [ForeignKey("ProgramRevID")]
    [InverseProperty("Staging_Policy")]
    public virtual ProgramRevision ProgramRev { get; set; }

    [InverseProperty("Quote")]
    public virtual ICollection<Staging_Driver> Staging_Driver { get; set; } = new List<Staging_Driver>();
}