// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CommonAPIDAL.VisionAppModels
{
    public partial class uspGetVINDataByManufacturerIDLegacyResult
    {
        public int vinID { get; set; }
        public string VIN { get; set; }
        public short ModelYear { get; set; }
        public DateTime? EffDate { get; set; }
        public string MakeCode { get; set; }
        public int? MakeID { get; set; }
        public string Make { get; set; }
        public string MakeAbbr { get; set; }
        public string ShortModel { get; set; }
        public string FullModel { get; set; }
        public string ISOSymbol { get; set; }
        public string CompSymbol { get; set; }
        public string CollSymbol { get; set; }
        public string BodyStyle { get; set; }
        public string LiabBodyStyle { get; set; }
        public string BodyStyleDesc { get; set; }
        public string RestraintInd { get; set; }
        public string AntiTheftInd { get; set; }
        public string FourWheelDriveInd { get; set; }
        public string Cylinders { get; set; }
        public string EngineType { get; set; }
        public string EngineSize { get; set; }
        public string EngineInfo { get; set; }
        public string ClassCode { get; set; }
        public string DayTimeRunningLightInd { get; set; }
        public string AntiLockInd { get; set; }
        public string TransmissionInfo { get; set; }
        public string StateException { get; set; }
        public string WheelBaseInfo { get; set; }
        public string SpecialInfoSelector { get; set; }
        public string PIPSymbol { get; set; }
        public string LiabilitySymbol { get; set; }
    }
}
