// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CommonAPIDAL.VisionAppModels
{
    public partial class uspGetVINDataByManufacturerIDResult
    {
        public int VinID { get; set; }
        public int? MakeID { get; set; }
        public string VIN { get; set; }
        public string ISONumber { get; set; }
        public short ModelYear { get; set; }
        public string VINChangeInd { get; set; }
        public DateTime? EffDate { get; set; }
        public string RestraintInd { get; set; }
        public string AntiLockInd { get; set; }
        public string Cylinders { get; set; }
        public string EngineType { get; set; }
        public string FieldChangeInd { get; set; }
        public string MakeCode { get; set; }
        public string ShortModel { get; set; }
        public string BodyStyle { get; set; }
        public string EngineSize { get; set; }
        public string FourWheelDriveInd { get; set; }
        public string FullModel { get; set; }
        public string SpecialInfoSelector { get; set; }
        public string ModelInfo { get; set; }
        public string BodyInfo { get; set; }
        public string EngineInfo { get; set; }
        public string TransmissionInfo { get; set; }
        public string NotOtherwiseClassifiedInfo { get; set; }
        public string DayTimeRunningLightInd { get; set; }
        public string WheelbaseInfo { get; set; }
        public string ClassCode { get; set; }
        public string CurbWeight { get; set; }
        public string GrossVehicleWeight { get; set; }
        public string Height { get; set; }
        public string HorsePower { get; set; }
        public string StateException { get; set; }
        public string VMPerformanceInd { get; set; }
        public string ElectronStabilityCtl { get; set; }
        public string TonnageInd { get; set; }
        public short? PayloadCapacity { get; set; }
        public string NCIC_Manufacturer { get; set; }
        public string CompSymbol { get; set; }
        public string CollSymbol { get; set; }
        public string NewPriceSymbol { get; set; }
        public string BiSymbol { get; set; }
        public string PDSymbol { get; set; }
        public string MedPaySymbol { get; set; }
        public string PIPSymbol { get; set; }
        public string Make { get; set; }
        public string MakeAbbr { get; set; }
        public string BodyStyleDesc { get; set; }
        public string ModelInfoDescription { get; set; }
    }
}
