// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("VIN_BodyStyle", Schema = "dbo")]
public partial class VIN_BodyStyle
{
    [Key]
    public int bsID { get; set; }

    [Required]
    [StringLength(8)]
    [Unicode(false)]
    public string BodyStyle { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string BodyStyleDesc { get; set; }
}