// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("VIN_ModelInfo", Schema = "dbo")]
public partial class VIN_ModelInfo
{
    [Key]
    [StringLength(4)]
    [Unicode(false)]
    public string ModelInfo { get; set; }

    public string ModelInfoDescription { get; set; }
}