// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.VisionAppModels;

[Table("WebPDFs", Schema = "dbo")]
[Index("PolicyNo", Name = "IX_PolicyNo")]
[Index("DocumentName", Name = "IX_WebPDFs_DocumentName")]
[Index("DocumentName", "FileLocation", Name = "IX_WebPDFs_DocumentName_FileLocation")]
[Index("DownloadFile", "quoteID", Name = "IX_WebPDFs_DownloadFile_quoteID")]
[Index("quoteID", "ticket", "FileLocation", Name = "IX_WebPDFs_quote")]
[Index("quoteID", Name = "IX_WebPDFs_quoteID")]
[Index("wdpfID", "ticket", "pdforder", "quoteID", "PolicyNo", Name = "NonClusteredIndex-20160701-142248")]
public partial class WebPDFs
{
    [Key]
    public int wdpfID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string ticket { get; set; }

    public int pdforder { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string DocumentName { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string DownloadFile { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime dateAdded { get; set; }

    public int quoteID { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string FileLocation { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string OldFileLocation { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PolicyNo { get; set; }
}