// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.BBDBModels;

[Table("CreditReport", Schema = "dbo")]
public partial class CreditReport
{
    [Key]
    public int cID { get; set; }

    public int rmID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string PolType { get; set; }

    public short Score { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ReferenceNum { get; set; }

    [ForeignKey("rmID")]
    [InverseProperty("CreditReport")]
    public virtual ResultMaster rm { get; set; }
}