// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CommonAPIDAL.BBDBModels;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace CommonAPIDAL.BBDBModels
{
    public partial interface IBBDBEntitiesProcedures
    {
        Task<int> uspDrivers_From_ISO_Insert_LYAsync(int? quoteID, int? driverCount, string FirstName, string MiddleName, string LastName, string DLNumber, string DateOfBirth, string SSN, string Gender, string Address, string City, string State, string Zipcode, int? ISOMasterID, OutputParameter<int?> rowID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspDrivers_From_ISO_Select_LYResult>> uspDrivers_From_ISO_Select_LYAsync(int? isoMasterId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspDrivers_From_Prefill_Driver_Select_LYResult>> uspDrivers_From_Prefill_Driver_Select_LYAsync(int? quoteID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspDrivers_From_Previous_Prefill_Driver_Select_LYResult>> uspDrivers_From_Previous_Prefill_Driver_Select_LYAsync(int? quoteID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> uspISORawXML_InsertAsync(int? quoteID, string Name, string Type, string Data, int? ResponseTime, string XMLSentToISO, string RequestID, string Product, string LexID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspPolicies_From_PrefillPolicyDatasResult>> uspPolicies_From_PrefillPolicyDatasAsync(int? isoMasterId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspVehicles_From_Prefill_Vehicle_Select_LYResult>> uspVehicles_From_Prefill_Vehicle_Select_LYAsync(int? quoteID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> uspVSRawXML_InsertAsync(int? quoteID, string Name, string Data, int? ResponseTime, string XMLSentToRM, string RequestID, string ErrorMessage, string RequestJS, string ResponseJS, OutputParameter<int?> RetVal, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspXML_ISO_Data_ViewResult>> uspXML_ISO_Data_ViewAsync(int? HdrID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
