// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.BBDBModels;

[Table("ISO_XML_Backup_Hdr", Schema = "dbo")]
[Index("Status", "Date", "Product", Name = "IX_ISO_XML_Backup_Hdr_Status_Date_Product")]
public partial class ISO_XML_Backup_Hdr
{
    [Key]
    public int HdrID { get; set; }

    public int? QuoteID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [StringLength(35)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    public int? ISOResponseMilliSecs { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string RequestID { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Product { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LexID { get; set; }
}