// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.BBDBModels;

[Table("ISOMaster", Schema = "dbo")]
[Index("FirstName", "LastName", "Address", "City", "ISOState", "Zip", "CreateDate", Name = "IX_ISOMaster_FNLNADDRCTYSTZPCRDT")]
[Index("QuoteId", "NewRecord", Name = "IX_ISOMaster_QuoteId_NewRecord")]
public partial class ISOMaster
{
    [Key]
    public int ISOMasterID { get; set; }

    public int QuoteId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string MiddleInitial { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Address { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string City { get; set; }

    [Required]
    [StringLength(2)]
    [Unicode(false)]
    public string ISOState { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Zip { get; set; }

    [StringLength(14)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    public bool? NewRecord { get; set; }

    [InverseProperty("ISOMaster")]
    public virtual ICollection<PolicyCoverageInterval> PolicyCoverageInterval { get; set; } = new List<PolicyCoverageInterval>();

    [InverseProperty("ISOMaster")]
    public virtual ICollection<PolicyData> PolicyData { get; set; } = new List<PolicyData>();
}