// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.BBDBModels;

[Table("PolicyData", Schema = "dbo")]
[Index("ISOMasterId", "PolicyHolderName", Name = "IX_PolicyData_ISOMasterId_PolicyHolderName")]
public partial class PolicyData
{
    [Key]
    public int Id { get; set; }

    public int ISOMasterId { get; set; }

    [Required]
    [StringLength(50)]
    public string CarrierName { get; set; }

    [Required]
    [StringLength(50)]
    public string PolicyNumber { get; set; }

    [Required]
    [StringLength(50)]
    public string PolicyStatus { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime InceptionDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastReportedTermEffectiveDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastReportedTermExpirationDate { get; set; }

    public int NumberOfCancellations { get; set; }

    public int NumberOfRenewals { get; set; }

    public int BIIndividualLimit { get; set; }

    public int BIOccuranceLimit { get; set; }

    public int CSILimit { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CoverageFromDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CoverageToDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ReportAsOfDate { get; set; }

    public bool IsStandardPolicy { get; set; }

    [Required]
    [StringLength(50)]
    public string PolicyType { get; set; }

    [StringLength(2)]
    public string PolicyState { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastCancelDate { get; set; }

    [StringLength(50)]
    public string CancelReason { get; set; }

    [StringLength(50)]
    public string NAIC { get; set; }

    [StringLength(50)]
    public string PolicyHolderName { get; set; }

    [ForeignKey("ISOMasterId")]
    [InverseProperty("PolicyData")]
    public virtual ISOMaster ISOMaster { get; set; }

    [InverseProperty("Policy")]
    public virtual ICollection<PolicySubject> PolicySubject { get; set; } = new List<PolicySubject>();
}