// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.BBDBModels;

[Table("PolicyCoverageInterval", Schema = "dbo")]
public partial class PolicyCoverageInterval
{
    [Key]
    public int Id { get; set; }

    public int ISOMasterId { get; set; }

    [Required]
    [StringLength(50)]
    public string Company { get; set; }

    [Required]
    [StringLength(50)]
    public string AMBest { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FromDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ToDate { get; set; }

    public int CoverageDays { get; set; }

    [StringLength(2)]
    public string BreakFromPrior { get; set; }

    public int LapsedDays { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? InceptionDate { get; set; }

    [StringLength(275)]
    [Unicode(false)]
    public string LapseReason { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PolicyHolderName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PolicyHolderRelationship { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string SubjectUnitNumber { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PolicyNumber { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string PolicyStatus { get; set; }

    [ForeignKey("ISOMasterId")]
    [InverseProperty("PolicyCoverageInterval")]
    public virtual ISOMaster ISOMaster { get; set; }
}