// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.BBDBModels;

[Table("PolicySubject", Schema = "dbo")]
[Index("PolicyId", Name = "IX_PolicySubject_PolicyId")]
public partial class PolicySubject
{
    [Key]
    public int Id { get; set; }

    public int PolicyId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(50)]
    public string RelationCode { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FromDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ToDate { get; set; }

    [StringLength(50)]
    public string RelationCodeDesc { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string SubjectId { get; set; }

    [ForeignKey("PolicyId")]
    [InverseProperty("PolicySubject")]
    public virtual PolicyData Policy { get; set; }

    [InverseProperty("PolicySubject")]
    public virtual ICollection<PolicySubjectHistory> PolicySubjectHistory { get; set; } = new List<PolicySubjectHistory>();
}