// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.BBDBModels;

[Table("PolicySubjectHistory", Schema = "dbo")]
[Index("PolicySubjectId", Name = "IX_PolicySubjectHistory_PolicySubjectId")]
public partial class PolicySubjectHistory
{
    [Key]
    public int Id { get; set; }

    public int PolicySubjectId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FromDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ToDate { get; set; }

    [ForeignKey("PolicySubjectId")]
    [InverseProperty("PolicySubjectHistory")]
    public virtual PolicySubject PolicySubject { get; set; }
}