// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.BBDBModels;

[Table("PrefillPolicyData", Schema = "dbo")]
public partial class PrefillPolicyData
{
    [Key]
    public int PrefillPolicyID { get; set; }

    public int QuoteID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string PolicyNumber { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string PolicyType { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string PolicyStatus { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string CarrierName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string AmbestNumber { get; set; }

    public DateTime InceptionDate { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime LastCancelDate { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Occurences { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string SubjectUnitNumber { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string PolicyHolderName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string PolicyHolderRelationship { get; set; }

    public DateTime PolicyFromDate { get; set; }

    public DateTime PolicyToDate { get; set; }

    public int? IsoMasterId { get; set; }
}