// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.BBDBModels;

[Table("ResultMaster", Schema = "dbo")]
public partial class ResultMaster
{
    [Key]
    public int rmID { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime OrderDate { get; set; }

    [Required]
    [StringLength(11)]
    [Unicode(false)]
    public string NI_SSN { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime NI_DOB { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string NI_LicenseNum { get; set; }

    public bool? CCAcceptance { get; set; }

    [Required]
    [StringLength(50)]
    public string NameFirst { get; set; }

    [Required]
    [StringLength(50)]
    public string NameLast { get; set; }

    [Required]
    [StringLength(100)]
    public string Address { get; set; }

    [Required]
    [StringLength(50)]
    public string City { get; set; }

    [Required]
    [StringLength(2)]
    [Unicode(false)]
    public string State { get; set; }

    [Required]
    [StringLength(11)]
    [Unicode(false)]
    public string Zip { get; set; }

    [InverseProperty("rm")]
    public virtual ICollection<CreditReport> CreditReport { get; set; } = new List<CreditReport>();
}