// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommonAPIDAL.BBDBModels;

[Table("RMTVehicleScores", Schema = "dbo")]
[Index("HdrId", Name = "IXNC_RMTVehicleScores_HdrId")]
[Index("VIN", Name = "IXNC_RMTVehicleScores_VIN")]
public partial class RMTVehicleScores
{
    [Key]
    public int vsID { get; set; }

    public int HdrId { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime OrderDate { get; set; }

    [Required]
    [StringLength(50)]
    public string VIN { get; set; }

    [Required]
    [StringLength(3)]
    [Unicode(false)]
    public string VINScore { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Source { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string ScoreError { get; set; }

    public int? Quoteid { get; set; }

    public byte? RequestState { get; set; }
}