// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CommonAPIDAL.BBDBModels
{
    public partial class uspDrivers_From_Previous_Prefill_Driver_Select_LYResult
    {
        public string DrvFirstName { get; set; }
        public string DrvLastName { get; set; }
        public string IsoDriverDOB { get; set; }
        public DateTime? StagingDriverDOB { get; set; }
        public int? sdID { get; set; }
    }
}
