// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CommonAPIDAL.BBDBModels
{
    public partial class uspDrivers_From_ISO_Select_LYResult
    {
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string DLNumber { get; set; }
        public string DateOfBirth { get; set; }
        public string SSN { get; set; }
        public string Gender { get; set; }
        public int rowID { get; set; }
    }
}
