// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CommonAPIDAL.BBDBModels
{
    public partial class uspVehicles_From_Prefill_Vehicle_Select_LYResult
    {
        public int? svID { get; set; }
        public int? QuoteID { get; set; }
        public int? MakeID { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public short? ModelYear { get; set; }
        public string VIN { get; set; }
    }
}
