// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CommonAPIDAL.BBDBModels
{
    public partial class uspXML_ISO_Data_ViewResult
    {
        public int? QuoteID { get; set; }
        public DateTime Date { get; set; }
        public int? ISOResponseMilliSecs { get; set; }
        public string XMLTo { get; set; }
        public string XMLFrom { get; set; }
    }
}
