//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPInquiry
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://attract30inquiry.vsn.com", ConfigurationName="CPInquiry.CPInquiryWebservice")]
    public interface CPInquiryWebservice
    {
        
        // CODEGEN: Parameter 'submitCPRequestITCReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="submitCPRequestITCReturn")]
        CPInquiry.submitCPRequestITCResponse submitCPRequestITC(CPInquiry.submitCPRequestITCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CPInquiry.submitCPRequestITCResponse> submitCPRequestITCAsync(CPInquiry.submitCPRequestITCRequest request);
        
        // CODEGEN: Parameter 'submitCPRequestObjectReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="submitCPRequestObjectReturn")]
        CPInquiry.submitCPRequestObjectResponse submitCPRequestObject(CPInquiry.submitCPRequestObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CPInquiry.submitCPRequestObjectResponse> submitCPRequestObjectAsync(CPInquiry.submitCPRequestObjectRequest request);
        
        // CODEGEN: Parameter 'submitCPRequestReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="submitCPRequestReturn")]
        CPInquiry.submitCPRequestResponse submitCPRequest(CPInquiry.submitCPRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CPInquiry.submitCPRequestResponse> submitCPRequestAsync(CPInquiry.submitCPRequestRequest request);
        
        // CODEGEN: Parameter 'submitCPRequestQAEnvReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="submitCPRequestQAEnvReturn")]
        CPInquiry.submitCPRequestQAEnvResponse submitCPRequestQAEnv(CPInquiry.submitCPRequestQAEnvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CPInquiry.submitCPRequestQAEnvResponse> submitCPRequestQAEnvAsync(CPInquiry.submitCPRequestQAEnvRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="submitCPRequestITC", WrapperNamespace="http://attract30inquiry.vsn.com", IsWrapped=true)]
    public partial class submitCPRequestITCRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string clientID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string namePrefix;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string nameFirst;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string nameMiddle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string nameLast;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string nameSuffix;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string dob;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string age;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ssn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string houseNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string streetName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string apartmentNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string city;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string state;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string zip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=16)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string zipPlus4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=17)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string licenseNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=18)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string licenseState;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=19)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string products;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=20)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string agentSuffix;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=21)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string itcIndicator;
        
        public submitCPRequestITCRequest()
        {
        }
        
        public submitCPRequestITCRequest(
                    string clientID, 
                    string namePrefix, 
                    string nameFirst, 
                    string nameMiddle, 
                    string nameLast, 
                    string nameSuffix, 
                    string dob, 
                    string age, 
                    string sex, 
                    string ssn, 
                    string houseNumber, 
                    string streetName, 
                    string apartmentNumber, 
                    string city, 
                    string state, 
                    string zip, 
                    string zipPlus4, 
                    string licenseNum, 
                    string licenseState, 
                    string products, 
                    string agentSuffix, 
                    string itcIndicator)
        {
            this.clientID = clientID;
            this.namePrefix = namePrefix;
            this.nameFirst = nameFirst;
            this.nameMiddle = nameMiddle;
            this.nameLast = nameLast;
            this.nameSuffix = nameSuffix;
            this.dob = dob;
            this.age = age;
            this.sex = sex;
            this.ssn = ssn;
            this.houseNumber = houseNumber;
            this.streetName = streetName;
            this.apartmentNumber = apartmentNumber;
            this.city = city;
            this.state = state;
            this.zip = zip;
            this.zipPlus4 = zipPlus4;
            this.licenseNum = licenseNum;
            this.licenseState = licenseState;
            this.products = products;
            this.agentSuffix = agentSuffix;
            this.itcIndicator = itcIndicator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="submitCPRequestITCResponse", WrapperNamespace="http://attract30inquiry.vsn.com", IsWrapped=true)]
    public partial class submitCPRequestITCResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int submitCPRequestITCReturn;
        
        public submitCPRequestITCResponse()
        {
        }
        
        public submitCPRequestITCResponse(int submitCPRequestITCReturn)
        {
            this.submitCPRequestITCReturn = submitCPRequestITCReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://attract30inquiry.vsn.com")]
    public partial class CPRequestData
    {
        
        private string clientIDField;
        
        private string namePrefixField;
        
        private string nameLastField;
        
        private string nameFirstField;
        
        private string nameMiddleField;
        
        private string nameSuffixField;
        
        private string dobField;
        
        private string ageField;
        
        private string sexField;
        
        private string sSNField;
        
        private string houseNumberField;
        
        private string streetNameField;
        
        private string apartmentNumberField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string zipPlus4Field;
        
        private string licenseNumField;
        
        private string licenseStateField;
        
        private string productsField;
        
        private string agentSuffixField;
        
        private string iTCIndicatorField;
        
        private int qAEnvField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string clientID
        {
            get
            {
                return this.clientIDField;
            }
            set
            {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string namePrefix
        {
            get
            {
                return this.namePrefixField;
            }
            set
            {
                this.namePrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string nameLast
        {
            get
            {
                return this.nameLastField;
            }
            set
            {
                this.nameLastField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string nameFirst
        {
            get
            {
                return this.nameFirstField;
            }
            set
            {
                this.nameFirstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string nameMiddle
        {
            get
            {
                return this.nameMiddleField;
            }
            set
            {
                this.nameMiddleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string nameSuffix
        {
            get
            {
                return this.nameSuffixField;
            }
            set
            {
                this.nameSuffixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string dob
        {
            get
            {
                return this.dobField;
            }
            set
            {
                this.dobField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string age
        {
            get
            {
                return this.ageField;
            }
            set
            {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string sex
        {
            get
            {
                return this.sexField;
            }
            set
            {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string SSN
        {
            get
            {
                return this.sSNField;
            }
            set
            {
                this.sSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string houseNumber
        {
            get
            {
                return this.houseNumberField;
            }
            set
            {
                this.houseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string streetName
        {
            get
            {
                return this.streetNameField;
            }
            set
            {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string apartmentNumber
        {
            get
            {
                return this.apartmentNumberField;
            }
            set
            {
                this.apartmentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public string zipPlus4
        {
            get
            {
                return this.zipPlus4Field;
            }
            set
            {
                this.zipPlus4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public string licenseNum
        {
            get
            {
                return this.licenseNumField;
            }
            set
            {
                this.licenseNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public string licenseState
        {
            get
            {
                return this.licenseStateField;
            }
            set
            {
                this.licenseStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=19)]
        public string products
        {
            get
            {
                return this.productsField;
            }
            set
            {
                this.productsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=20)]
        public string agentSuffix
        {
            get
            {
                return this.agentSuffixField;
            }
            set
            {
                this.agentSuffixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=21)]
        public string ITCIndicator
        {
            get
            {
                return this.iTCIndicatorField;
            }
            set
            {
                this.iTCIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public int QAEnv
        {
            get
            {
                return this.qAEnvField;
            }
            set
            {
                this.qAEnvField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="submitCPRequestObject", WrapperNamespace="http://attract30inquiry.vsn.com", IsWrapped=true)]
    public partial class submitCPRequestObjectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public CPInquiry.CPRequestData data;
        
        public submitCPRequestObjectRequest()
        {
        }
        
        public submitCPRequestObjectRequest(CPInquiry.CPRequestData data)
        {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="submitCPRequestObjectResponse", WrapperNamespace="http://attract30inquiry.vsn.com", IsWrapped=true)]
    public partial class submitCPRequestObjectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int submitCPRequestObjectReturn;
        
        public submitCPRequestObjectResponse()
        {
        }
        
        public submitCPRequestObjectResponse(int submitCPRequestObjectReturn)
        {
            this.submitCPRequestObjectReturn = submitCPRequestObjectReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="submitCPRequest", WrapperNamespace="http://attract30inquiry.vsn.com", IsWrapped=true)]
    public partial class submitCPRequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string clientID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string namePrefix;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string nameFirst;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string nameMiddle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string nameLast;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string nameSuffix;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string dob;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string age;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ssn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string houseNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string streetName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string apartmentNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string city;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string state;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string zip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=16)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string zipPlus4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=17)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string licenseNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=18)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string licenseState;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=19)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string products;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=20)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string agentSuffix;
        
        public submitCPRequestRequest()
        {
        }
        
        public submitCPRequestRequest(
                    string clientID, 
                    string namePrefix, 
                    string nameFirst, 
                    string nameMiddle, 
                    string nameLast, 
                    string nameSuffix, 
                    string dob, 
                    string age, 
                    string sex, 
                    string ssn, 
                    string houseNumber, 
                    string streetName, 
                    string apartmentNumber, 
                    string city, 
                    string state, 
                    string zip, 
                    string zipPlus4, 
                    string licenseNum, 
                    string licenseState, 
                    string products, 
                    string agentSuffix)
        {
            this.clientID = clientID;
            this.namePrefix = namePrefix;
            this.nameFirst = nameFirst;
            this.nameMiddle = nameMiddle;
            this.nameLast = nameLast;
            this.nameSuffix = nameSuffix;
            this.dob = dob;
            this.age = age;
            this.sex = sex;
            this.ssn = ssn;
            this.houseNumber = houseNumber;
            this.streetName = streetName;
            this.apartmentNumber = apartmentNumber;
            this.city = city;
            this.state = state;
            this.zip = zip;
            this.zipPlus4 = zipPlus4;
            this.licenseNum = licenseNum;
            this.licenseState = licenseState;
            this.products = products;
            this.agentSuffix = agentSuffix;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="submitCPRequestResponse", WrapperNamespace="http://attract30inquiry.vsn.com", IsWrapped=true)]
    public partial class submitCPRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int submitCPRequestReturn;
        
        public submitCPRequestResponse()
        {
        }
        
        public submitCPRequestResponse(int submitCPRequestReturn)
        {
            this.submitCPRequestReturn = submitCPRequestReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="submitCPRequestQAEnv", WrapperNamespace="http://attract30inquiry.vsn.com", IsWrapped=true)]
    public partial class submitCPRequestQAEnvRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string clientID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string namePrefix;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string nameFirst;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string nameMiddle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string nameLast;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string nameSuffix;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string dob;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string age;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ssn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string houseNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string streetName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string apartmentNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string city;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string state;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string zip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=16)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string zipPlus4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=17)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string licenseNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=18)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string licenseState;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=19)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string products;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=20)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string agentSuffix;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=21)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string itcIndicator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=22)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int qaEnv;
        
        public submitCPRequestQAEnvRequest()
        {
        }
        
        public submitCPRequestQAEnvRequest(
                    string clientID, 
                    string namePrefix, 
                    string nameFirst, 
                    string nameMiddle, 
                    string nameLast, 
                    string nameSuffix, 
                    string dob, 
                    string age, 
                    string sex, 
                    string ssn, 
                    string houseNumber, 
                    string streetName, 
                    string apartmentNumber, 
                    string city, 
                    string state, 
                    string zip, 
                    string zipPlus4, 
                    string licenseNum, 
                    string licenseState, 
                    string products, 
                    string agentSuffix, 
                    string itcIndicator, 
                    int qaEnv)
        {
            this.clientID = clientID;
            this.namePrefix = namePrefix;
            this.nameFirst = nameFirst;
            this.nameMiddle = nameMiddle;
            this.nameLast = nameLast;
            this.nameSuffix = nameSuffix;
            this.dob = dob;
            this.age = age;
            this.sex = sex;
            this.ssn = ssn;
            this.houseNumber = houseNumber;
            this.streetName = streetName;
            this.apartmentNumber = apartmentNumber;
            this.city = city;
            this.state = state;
            this.zip = zip;
            this.zipPlus4 = zipPlus4;
            this.licenseNum = licenseNum;
            this.licenseState = licenseState;
            this.products = products;
            this.agentSuffix = agentSuffix;
            this.itcIndicator = itcIndicator;
            this.qaEnv = qaEnv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="submitCPRequestQAEnvResponse", WrapperNamespace="http://attract30inquiry.vsn.com", IsWrapped=true)]
    public partial class submitCPRequestQAEnvResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://attract30inquiry.vsn.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int submitCPRequestQAEnvReturn;
        
        public submitCPRequestQAEnvResponse()
        {
        }
        
        public submitCPRequestQAEnvResponse(int submitCPRequestQAEnvReturn)
        {
            this.submitCPRequestQAEnvReturn = submitCPRequestQAEnvReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface CPInquiryWebserviceChannel : CPInquiry.CPInquiryWebservice, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class CPInquiryWebserviceClient : System.ServiceModel.ClientBase<CPInquiry.CPInquiryWebservice>, CPInquiry.CPInquiryWebservice
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CPInquiryWebserviceClient() : 
                base(CPInquiryWebserviceClient.GetDefaultBinding(), CPInquiryWebserviceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CPInquiryWebservice.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CPInquiryWebserviceClient(EndpointConfiguration endpointConfiguration) : 
                base(CPInquiryWebserviceClient.GetBindingForEndpoint(endpointConfiguration), CPInquiryWebserviceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CPInquiryWebserviceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CPInquiryWebserviceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CPInquiryWebserviceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CPInquiryWebserviceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CPInquiryWebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CPInquiry.submitCPRequestITCResponse CPInquiry.CPInquiryWebservice.submitCPRequestITC(CPInquiry.submitCPRequestITCRequest request)
        {
            return base.Channel.submitCPRequestITC(request);
        }
        
        public int submitCPRequestITC(
                    string clientID, 
                    string namePrefix, 
                    string nameFirst, 
                    string nameMiddle, 
                    string nameLast, 
                    string nameSuffix, 
                    string dob, 
                    string age, 
                    string sex, 
                    string ssn, 
                    string houseNumber, 
                    string streetName, 
                    string apartmentNumber, 
                    string city, 
                    string state, 
                    string zip, 
                    string zipPlus4, 
                    string licenseNum, 
                    string licenseState, 
                    string products, 
                    string agentSuffix, 
                    string itcIndicator)
        {
            CPInquiry.submitCPRequestITCRequest inValue = new CPInquiry.submitCPRequestITCRequest();
            inValue.clientID = clientID;
            inValue.namePrefix = namePrefix;
            inValue.nameFirst = nameFirst;
            inValue.nameMiddle = nameMiddle;
            inValue.nameLast = nameLast;
            inValue.nameSuffix = nameSuffix;
            inValue.dob = dob;
            inValue.age = age;
            inValue.sex = sex;
            inValue.ssn = ssn;
            inValue.houseNumber = houseNumber;
            inValue.streetName = streetName;
            inValue.apartmentNumber = apartmentNumber;
            inValue.city = city;
            inValue.state = state;
            inValue.zip = zip;
            inValue.zipPlus4 = zipPlus4;
            inValue.licenseNum = licenseNum;
            inValue.licenseState = licenseState;
            inValue.products = products;
            inValue.agentSuffix = agentSuffix;
            inValue.itcIndicator = itcIndicator;
            CPInquiry.submitCPRequestITCResponse retVal = ((CPInquiry.CPInquiryWebservice)(this)).submitCPRequestITC(inValue);
            return retVal.submitCPRequestITCReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPInquiry.submitCPRequestITCResponse> CPInquiry.CPInquiryWebservice.submitCPRequestITCAsync(CPInquiry.submitCPRequestITCRequest request)
        {
            return base.Channel.submitCPRequestITCAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPInquiry.submitCPRequestITCResponse> submitCPRequestITCAsync(
                    string clientID, 
                    string namePrefix, 
                    string nameFirst, 
                    string nameMiddle, 
                    string nameLast, 
                    string nameSuffix, 
                    string dob, 
                    string age, 
                    string sex, 
                    string ssn, 
                    string houseNumber, 
                    string streetName, 
                    string apartmentNumber, 
                    string city, 
                    string state, 
                    string zip, 
                    string zipPlus4, 
                    string licenseNum, 
                    string licenseState, 
                    string products, 
                    string agentSuffix, 
                    string itcIndicator)
        {
            CPInquiry.submitCPRequestITCRequest inValue = new CPInquiry.submitCPRequestITCRequest();
            inValue.clientID = clientID;
            inValue.namePrefix = namePrefix;
            inValue.nameFirst = nameFirst;
            inValue.nameMiddle = nameMiddle;
            inValue.nameLast = nameLast;
            inValue.nameSuffix = nameSuffix;
            inValue.dob = dob;
            inValue.age = age;
            inValue.sex = sex;
            inValue.ssn = ssn;
            inValue.houseNumber = houseNumber;
            inValue.streetName = streetName;
            inValue.apartmentNumber = apartmentNumber;
            inValue.city = city;
            inValue.state = state;
            inValue.zip = zip;
            inValue.zipPlus4 = zipPlus4;
            inValue.licenseNum = licenseNum;
            inValue.licenseState = licenseState;
            inValue.products = products;
            inValue.agentSuffix = agentSuffix;
            inValue.itcIndicator = itcIndicator;
            return ((CPInquiry.CPInquiryWebservice)(this)).submitCPRequestITCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CPInquiry.submitCPRequestObjectResponse CPInquiry.CPInquiryWebservice.submitCPRequestObject(CPInquiry.submitCPRequestObjectRequest request)
        {
            return base.Channel.submitCPRequestObject(request);
        }
        
        public int submitCPRequestObject(CPInquiry.CPRequestData data)
        {
            CPInquiry.submitCPRequestObjectRequest inValue = new CPInquiry.submitCPRequestObjectRequest();
            inValue.data = data;
            CPInquiry.submitCPRequestObjectResponse retVal = ((CPInquiry.CPInquiryWebservice)(this)).submitCPRequestObject(inValue);
            return retVal.submitCPRequestObjectReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPInquiry.submitCPRequestObjectResponse> CPInquiry.CPInquiryWebservice.submitCPRequestObjectAsync(CPInquiry.submitCPRequestObjectRequest request)
        {
            return base.Channel.submitCPRequestObjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPInquiry.submitCPRequestObjectResponse> submitCPRequestObjectAsync(CPInquiry.CPRequestData data)
        {
            CPInquiry.submitCPRequestObjectRequest inValue = new CPInquiry.submitCPRequestObjectRequest();
            inValue.data = data;
            return ((CPInquiry.CPInquiryWebservice)(this)).submitCPRequestObjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CPInquiry.submitCPRequestResponse CPInquiry.CPInquiryWebservice.submitCPRequest(CPInquiry.submitCPRequestRequest request)
        {
            return base.Channel.submitCPRequest(request);
        }
        
        public int submitCPRequest(
                    string clientID, 
                    string namePrefix, 
                    string nameFirst, 
                    string nameMiddle, 
                    string nameLast, 
                    string nameSuffix, 
                    string dob, 
                    string age, 
                    string sex, 
                    string ssn, 
                    string houseNumber, 
                    string streetName, 
                    string apartmentNumber, 
                    string city, 
                    string state, 
                    string zip, 
                    string zipPlus4, 
                    string licenseNum, 
                    string licenseState, 
                    string products, 
                    string agentSuffix)
        {
            CPInquiry.submitCPRequestRequest inValue = new CPInquiry.submitCPRequestRequest();
            inValue.clientID = clientID;
            inValue.namePrefix = namePrefix;
            inValue.nameFirst = nameFirst;
            inValue.nameMiddle = nameMiddle;
            inValue.nameLast = nameLast;
            inValue.nameSuffix = nameSuffix;
            inValue.dob = dob;
            inValue.age = age;
            inValue.sex = sex;
            inValue.ssn = ssn;
            inValue.houseNumber = houseNumber;
            inValue.streetName = streetName;
            inValue.apartmentNumber = apartmentNumber;
            inValue.city = city;
            inValue.state = state;
            inValue.zip = zip;
            inValue.zipPlus4 = zipPlus4;
            inValue.licenseNum = licenseNum;
            inValue.licenseState = licenseState;
            inValue.products = products;
            inValue.agentSuffix = agentSuffix;
            CPInquiry.submitCPRequestResponse retVal = ((CPInquiry.CPInquiryWebservice)(this)).submitCPRequest(inValue);
            return retVal.submitCPRequestReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPInquiry.submitCPRequestResponse> CPInquiry.CPInquiryWebservice.submitCPRequestAsync(CPInquiry.submitCPRequestRequest request)
        {
            return base.Channel.submitCPRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPInquiry.submitCPRequestResponse> submitCPRequestAsync(
                    string clientID, 
                    string namePrefix, 
                    string nameFirst, 
                    string nameMiddle, 
                    string nameLast, 
                    string nameSuffix, 
                    string dob, 
                    string age, 
                    string sex, 
                    string ssn, 
                    string houseNumber, 
                    string streetName, 
                    string apartmentNumber, 
                    string city, 
                    string state, 
                    string zip, 
                    string zipPlus4, 
                    string licenseNum, 
                    string licenseState, 
                    string products, 
                    string agentSuffix)
        {
            CPInquiry.submitCPRequestRequest inValue = new CPInquiry.submitCPRequestRequest();
            inValue.clientID = clientID;
            inValue.namePrefix = namePrefix;
            inValue.nameFirst = nameFirst;
            inValue.nameMiddle = nameMiddle;
            inValue.nameLast = nameLast;
            inValue.nameSuffix = nameSuffix;
            inValue.dob = dob;
            inValue.age = age;
            inValue.sex = sex;
            inValue.ssn = ssn;
            inValue.houseNumber = houseNumber;
            inValue.streetName = streetName;
            inValue.apartmentNumber = apartmentNumber;
            inValue.city = city;
            inValue.state = state;
            inValue.zip = zip;
            inValue.zipPlus4 = zipPlus4;
            inValue.licenseNum = licenseNum;
            inValue.licenseState = licenseState;
            inValue.products = products;
            inValue.agentSuffix = agentSuffix;
            return ((CPInquiry.CPInquiryWebservice)(this)).submitCPRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CPInquiry.submitCPRequestQAEnvResponse CPInquiry.CPInquiryWebservice.submitCPRequestQAEnv(CPInquiry.submitCPRequestQAEnvRequest request)
        {
            return base.Channel.submitCPRequestQAEnv(request);
        }
        
        public int submitCPRequestQAEnv(
                    string clientID, 
                    string namePrefix, 
                    string nameFirst, 
                    string nameMiddle, 
                    string nameLast, 
                    string nameSuffix, 
                    string dob, 
                    string age, 
                    string sex, 
                    string ssn, 
                    string houseNumber, 
                    string streetName, 
                    string apartmentNumber, 
                    string city, 
                    string state, 
                    string zip, 
                    string zipPlus4, 
                    string licenseNum, 
                    string licenseState, 
                    string products, 
                    string agentSuffix, 
                    string itcIndicator, 
                    int qaEnv)
        {
            CPInquiry.submitCPRequestQAEnvRequest inValue = new CPInquiry.submitCPRequestQAEnvRequest();
            inValue.clientID = clientID;
            inValue.namePrefix = namePrefix;
            inValue.nameFirst = nameFirst;
            inValue.nameMiddle = nameMiddle;
            inValue.nameLast = nameLast;
            inValue.nameSuffix = nameSuffix;
            inValue.dob = dob;
            inValue.age = age;
            inValue.sex = sex;
            inValue.ssn = ssn;
            inValue.houseNumber = houseNumber;
            inValue.streetName = streetName;
            inValue.apartmentNumber = apartmentNumber;
            inValue.city = city;
            inValue.state = state;
            inValue.zip = zip;
            inValue.zipPlus4 = zipPlus4;
            inValue.licenseNum = licenseNum;
            inValue.licenseState = licenseState;
            inValue.products = products;
            inValue.agentSuffix = agentSuffix;
            inValue.itcIndicator = itcIndicator;
            inValue.qaEnv = qaEnv;
            CPInquiry.submitCPRequestQAEnvResponse retVal = ((CPInquiry.CPInquiryWebservice)(this)).submitCPRequestQAEnv(inValue);
            return retVal.submitCPRequestQAEnvReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPInquiry.submitCPRequestQAEnvResponse> CPInquiry.CPInquiryWebservice.submitCPRequestQAEnvAsync(CPInquiry.submitCPRequestQAEnvRequest request)
        {
            return base.Channel.submitCPRequestQAEnvAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPInquiry.submitCPRequestQAEnvResponse> submitCPRequestQAEnvAsync(
                    string clientID, 
                    string namePrefix, 
                    string nameFirst, 
                    string nameMiddle, 
                    string nameLast, 
                    string nameSuffix, 
                    string dob, 
                    string age, 
                    string sex, 
                    string ssn, 
                    string houseNumber, 
                    string streetName, 
                    string apartmentNumber, 
                    string city, 
                    string state, 
                    string zip, 
                    string zipPlus4, 
                    string licenseNum, 
                    string licenseState, 
                    string products, 
                    string agentSuffix, 
                    string itcIndicator, 
                    int qaEnv)
        {
            CPInquiry.submitCPRequestQAEnvRequest inValue = new CPInquiry.submitCPRequestQAEnvRequest();
            inValue.clientID = clientID;
            inValue.namePrefix = namePrefix;
            inValue.nameFirst = nameFirst;
            inValue.nameMiddle = nameMiddle;
            inValue.nameLast = nameLast;
            inValue.nameSuffix = nameSuffix;
            inValue.dob = dob;
            inValue.age = age;
            inValue.sex = sex;
            inValue.ssn = ssn;
            inValue.houseNumber = houseNumber;
            inValue.streetName = streetName;
            inValue.apartmentNumber = apartmentNumber;
            inValue.city = city;
            inValue.state = state;
            inValue.zip = zip;
            inValue.zipPlus4 = zipPlus4;
            inValue.licenseNum = licenseNum;
            inValue.licenseState = licenseState;
            inValue.products = products;
            inValue.agentSuffix = agentSuffix;
            inValue.itcIndicator = itcIndicator;
            inValue.qaEnv = qaEnv;
            return ((CPInquiry.CPInquiryWebservice)(this)).submitCPRequestQAEnvAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CPInquiryWebservice))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CPInquiryWebservice))
            {
                return new System.ServiceModel.EndpointAddress("http://dc-4appwas02.vision-ins.net:9080/Attract30Inquiry/services/CPInquiryWebser" +
                        "vice");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CPInquiryWebserviceClient.GetBindingForEndpoint(EndpointConfiguration.CPInquiryWebservice);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CPInquiryWebserviceClient.GetEndpointAddress(EndpointConfiguration.CPInquiryWebservice);
        }
        
        public enum EndpointConfiguration
        {
            
            CPInquiryWebservice,
        }
    }
}
