//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriTech
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://agent.tritechsoft.com/AllocatorAgent/", ConfigurationName="TriTech.AgentPort")]
    public interface AgentPort
    {
        
        // CODEGEN: Generating message contract since the operation AllocateAddress is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CBaseClass))]
        TriTech.AllocateAddressResponse1 AllocateAddress(TriTech.AllocateAddress1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TriTech.AllocateAddressResponse1> AllocateAddressAsync(TriTech.AllocateAddress1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://agent.tritechsoft.com/AllocatorAgent/")]
    public partial class AllocateAddress
    {
        
        private string companyIDField;
        
        private string passwordField;
        
        private string sourceStreetField;
        
        private string sourceCityField;
        
        private string sourceStateField;
        
        private string sourceZipCodeField;
        
        private string lineOfBusinessField;
        
        private string effectiveDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CompanyID
        {
            get
            {
                return this.companyIDField;
            }
            set
            {
                this.companyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SourceStreet
        {
            get
            {
                return this.sourceStreetField;
            }
            set
            {
                this.sourceStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SourceCity
        {
            get
            {
                return this.sourceCityField;
            }
            set
            {
                this.sourceCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SourceState
        {
            get
            {
                return this.sourceStateField;
            }
            set
            {
                this.sourceStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SourceZipCode
        {
            get
            {
                return this.sourceZipCodeField;
            }
            set
            {
                this.sourceZipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LineOfBusiness
        {
            get
            {
                return this.lineOfBusinessField;
            }
            set
            {
                this.lineOfBusinessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string EffectiveDate
        {
            get
            {
                return this.effectiveDateField;
            }
            set
            {
                this.effectiveDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://agent.tritechsoft.com/AllocatorAgent/")]
    public partial class CTaxRates
    {
        
        private double casualtyField;
        
        private double fireField;
        
        private double healthField;
        
        private double inlandMarineField;
        
        private double lifeField;
        
        private double motorVehicleField;
        
        private double otherField;
        
        private double minTaxField;
        
        private double flatFeeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Casualty
        {
            get
            {
                return this.casualtyField;
            }
            set
            {
                this.casualtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Fire
        {
            get
            {
                return this.fireField;
            }
            set
            {
                this.fireField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Health
        {
            get
            {
                return this.healthField;
            }
            set
            {
                this.healthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double InlandMarine
        {
            get
            {
                return this.inlandMarineField;
            }
            set
            {
                this.inlandMarineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Life
        {
            get
            {
                return this.lifeField;
            }
            set
            {
                this.lifeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double MotorVehicle
        {
            get
            {
                return this.motorVehicleField;
            }
            set
            {
                this.motorVehicleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double Other
        {
            get
            {
                return this.otherField;
            }
            set
            {
                this.otherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double MinTax
        {
            get
            {
                return this.minTaxField;
            }
            set
            {
                this.minTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double FlatFee
        {
            get
            {
                return this.flatFeeField;
            }
            set
            {
                this.flatFeeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CAlloError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CMatchQuality))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CAddress))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CAlloResults))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://agent.tritechsoft.com/AllocatorAgent/")]
    public partial class CBaseClass
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://agent.tritechsoft.com/AllocatorAgent/")]
    public partial class CAlloError : CBaseClass
    {
        
        private int numberField;
        
        private string descriptionField;
        
        private string sourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://agent.tritechsoft.com/AllocatorAgent/")]
    public partial class CMatchQuality : CBaseClass
    {
        
        private short matchCodeField;
        
        private string matchDescriptionField;
        
        private string matchIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short MatchCode
        {
            get
            {
                return this.matchCodeField;
            }
            set
            {
                this.matchCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MatchDescription
        {
            get
            {
                return this.matchDescriptionField;
            }
            set
            {
                this.matchDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MatchIdentifier
        {
            get
            {
                return this.matchIdentifierField;
            }
            set
            {
                this.matchIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://agent.tritechsoft.com/AllocatorAgent/")]
    public partial class CAddress : CBaseClass
    {
        
        private string streetField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ZipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://agent.tritechsoft.com/AllocatorAgent/")]
    public partial class CAlloResults : CBaseClass
    {
        
        private CAddress sourceAddressField;
        
        private string lineOfBusinessField;
        
        private CAddress matchedAddressField;
        
        private string censusBlockIDField;
        
        private string countyFipsCodeField;
        
        private string censusCountyNameField;
        
        private string censusCountyCodeField;
        
        private CMatchQuality matchQualityField;
        
        private string cityCodeField;
        
        private string cityNameField;
        
        private string cityOrCountyField;
        
        private string taxCodeField;
        
        private CTaxRates cityTaxRatesField;
        
        private bool countyCreditAppliesField;
        
        private string countyCodeField;
        
        private string countyNameField;
        
        private CTaxRates countyTaxRatesField;
        
        private string effectiveDateField;
        
        private double effectiveTaxRateField;
        
        private double effectiveCityRateField;
        
        private double effectiveCountyRateField;
        
        private CAlloError errorDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CAddress SourceAddress
        {
            get
            {
                return this.sourceAddressField;
            }
            set
            {
                this.sourceAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LineOfBusiness
        {
            get
            {
                return this.lineOfBusinessField;
            }
            set
            {
                this.lineOfBusinessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CAddress MatchedAddress
        {
            get
            {
                return this.matchedAddressField;
            }
            set
            {
                this.matchedAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CensusBlockID
        {
            get
            {
                return this.censusBlockIDField;
            }
            set
            {
                this.censusBlockIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CountyFipsCode
        {
            get
            {
                return this.countyFipsCodeField;
            }
            set
            {
                this.countyFipsCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CensusCountyName
        {
            get
            {
                return this.censusCountyNameField;
            }
            set
            {
                this.censusCountyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CensusCountyCode
        {
            get
            {
                return this.censusCountyCodeField;
            }
            set
            {
                this.censusCountyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public CMatchQuality MatchQuality
        {
            get
            {
                return this.matchQualityField;
            }
            set
            {
                this.matchQualityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CityCode
        {
            get
            {
                return this.cityCodeField;
            }
            set
            {
                this.cityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CityName
        {
            get
            {
                return this.cityNameField;
            }
            set
            {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CityOrCounty
        {
            get
            {
                return this.cityOrCountyField;
            }
            set
            {
                this.cityOrCountyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string TaxCode
        {
            get
            {
                return this.taxCodeField;
            }
            set
            {
                this.taxCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public CTaxRates CityTaxRates
        {
            get
            {
                return this.cityTaxRatesField;
            }
            set
            {
                this.cityTaxRatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool CountyCreditApplies
        {
            get
            {
                return this.countyCreditAppliesField;
            }
            set
            {
                this.countyCreditAppliesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string CountyCode
        {
            get
            {
                return this.countyCodeField;
            }
            set
            {
                this.countyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CountyName
        {
            get
            {
                return this.countyNameField;
            }
            set
            {
                this.countyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public CTaxRates CountyTaxRates
        {
            get
            {
                return this.countyTaxRatesField;
            }
            set
            {
                this.countyTaxRatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string EffectiveDate
        {
            get
            {
                return this.effectiveDateField;
            }
            set
            {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public double EffectiveTaxRate
        {
            get
            {
                return this.effectiveTaxRateField;
            }
            set
            {
                this.effectiveTaxRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public double EffectiveCityRate
        {
            get
            {
                return this.effectiveCityRateField;
            }
            set
            {
                this.effectiveCityRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public double EffectiveCountyRate
        {
            get
            {
                return this.effectiveCountyRateField;
            }
            set
            {
                this.effectiveCountyRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public CAlloError ErrorDetails
        {
            get
            {
                return this.errorDetailsField;
            }
            set
            {
                this.errorDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://agent.tritechsoft.com/AllocatorAgent/")]
    public partial class AllocateAddressResponse
    {
        
        private CAlloResults allocateAddressResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CAlloResults AllocateAddressResult
        {
            get
            {
                return this.allocateAddressResultField;
            }
            set
            {
                this.allocateAddressResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllocateAddress1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://agent.tritechsoft.com/AllocatorAgent/", Order=0)]
        public TriTech.AllocateAddress AllocateAddress;
        
        public AllocateAddress1()
        {
        }
        
        public AllocateAddress1(TriTech.AllocateAddress AllocateAddress)
        {
            this.AllocateAddress = AllocateAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllocateAddressResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://agent.tritechsoft.com/AllocatorAgent/", Order=0)]
        public TriTech.AllocateAddressResponse AllocateAddressResponse;
        
        public AllocateAddressResponse1()
        {
        }
        
        public AllocateAddressResponse1(TriTech.AllocateAddressResponse AllocateAddressResponse)
        {
            this.AllocateAddressResponse = AllocateAddressResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface AgentPortChannel : TriTech.AgentPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class AgentPortClient : System.ServiceModel.ClientBase<TriTech.AgentPort>, TriTech.AgentPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AgentPortClient(EndpointConfiguration endpointConfiguration) : 
                base(AgentPortClient.GetBindingForEndpoint(endpointConfiguration), AgentPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AgentPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AgentPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AgentPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AgentPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AgentPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TriTech.AllocateAddressResponse1 TriTech.AgentPort.AllocateAddress(TriTech.AllocateAddress1 request)
        {
            return base.Channel.AllocateAddress(request);
        }
        
        public TriTech.AllocateAddressResponse AllocateAddress(TriTech.AllocateAddress AllocateAddress1)
        {
            TriTech.AllocateAddress1 inValue = new TriTech.AllocateAddress1();
            inValue.AllocateAddress = AllocateAddress1;
            TriTech.AllocateAddressResponse1 retVal = ((TriTech.AgentPort)(this)).AllocateAddress(inValue);
            return retVal.AllocateAddressResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TriTech.AllocateAddressResponse1> TriTech.AgentPort.AllocateAddressAsync(TriTech.AllocateAddress1 request)
        {
            return base.Channel.AllocateAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<TriTech.AllocateAddressResponse1> AllocateAddressAsync(TriTech.AllocateAddress AllocateAddress)
        {
            TriTech.AllocateAddress1 inValue = new TriTech.AllocateAddress1();
            inValue.AllocateAddress = AllocateAddress;
            return ((TriTech.AgentPort)(this)).AllocateAddressAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AgentPortSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AgentPortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AgentPortSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://api.agent.tritechsoft.com/AllocatorAgent/");
            }
            if ((endpointConfiguration == EndpointConfiguration.AgentPortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("https://api.agent.tritechsoft.com/AllocatorAgent/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AgentPortSoap12,
            
            AgentPortSoap11,
        }
    }
}
